//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int id { get; set; }
        public int reservation_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_method { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
